name: 刷步数

on:
  workflow_dispatch:
  schedule:
    - cron: 18 6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 开始
      run: |
        pip install requests
        python3 mimotion.py
      env:
       XMYD_USER: ${{ secrets.XMYD_USER }}  #必须
       XMYD_PASSWD: ${{ secrets.XMYD_PASSWD }}  #必须
       XMYD_STEP: ${{ secrets.XMYD_STEP }}  #必须:  
       TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
       TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
